/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Parte1Examen;
import java.util.Vector; //esto nos sirve para implementar filas en una tabla

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ubuntu
 */
public class spotify1 extends javax.swing.JFrame {

    /**
     * Creates new form spotify1
     */
    public spotify1() {
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        genero = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        TxtCancion = new javax.swing.JTextField();
        BtmAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtGeneral = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTsalsa = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTrock = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jRrock = new javax.swing.JRadioButton();
        jRsalsa = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("canción ");

        BtmAgregar.setText("Agregar");
        BtmAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtmAgregarActionPerformed(evt);
            }
        });

        jtGeneral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 2));
        jtGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "General"
            }
        ));
        jScrollPane1.setViewportView(jtGeneral);

        jTsalsa.setBackground(new java.awt.Color(255, 255, 102));
        jTsalsa.setForeground(new java.awt.Color(255, 0, 0));
        jTsalsa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SALSA"
            }
        ));
        jScrollPane2.setViewportView(jTsalsa);

        jTrock.setBackground(new java.awt.Color(204, 204, 204));
        jTrock.setFont(new java.awt.Font("Ani", 0, 15)); // NOI18N
        jTrock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "ROCK"
            }
        ));
        jScrollPane3.setViewportView(jTrock);

        genero.add(jRrock);
        jRrock.setText("Rock");

        genero.add(jRsalsa);
        jRsalsa.setSelected(true);
        jRsalsa.setText("Salsa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jRsalsa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jRrock)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRrock)
                    .addComponent(jRsalsa))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(80, 80, 80)
                .addComponent(TxtCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(BtmAgregar)
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(TxtCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtmAgregar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Lista playlist = new Lista();
public void Imprimir_TableGeneral(){
    Nodo iterador = playlist.primero; //declaramos el iterador 
    //limpiamos la tabla general
    DefaultTableModel modelGeneral = (DefaultTableModel) jtGeneral.getModel();
    modelGeneral.addRow(new Object[]{" "});
    for (int i = 0; i < jtGeneral.getRowCount(); i++) 
    {
        modelGeneral.removeRow(i);
        i-=1;
    }
    //limpiamos la tabla de salsa
    DefaultTableModel modelSalsa = (DefaultTableModel) jTsalsa.getModel();
    modelSalsa.addRow(new Object[]{" "});
    for (int i = 0; i < jTsalsa.getRowCount(); i++) 
    {
        modelSalsa.removeRow(i);
        i-=1;
    }
    //limpiamos la tabla de Rock
    DefaultTableModel modelRock = (DefaultTableModel) jTrock.getModel();
    modelRock.addRow(new Object[]{" "});
    for (int i = 0; i < jTrock.getRowCount(); i++) 
    {
        modelRock.removeRow(i);
        i-=1;
    }
    while(iterador.getCancion()!=null)
    {
        modelGeneral.addRow(new Object[]{iterador.getCancion()});
        if(iterador.getGenero()==1)
        {
            modelSalsa.addRow(new Object[]{iterador.getCancion()});
        }else{
            modelRock.addRow(new Object[]{iterador.getCancion()});
        }
        iterador = iterador.siguiente;
    }
}
//public void Imprimir_TableSalsa(){
//    Nodo iterador = playlist.primero;
//    DefaultTableModel modelSalsa = (DefaultTableModel) jTsalsa.getModel();
//    modelSalsa.addRow(new Object[]{" "});
//    for (int i = 0; i < jTsalsa.getRowCount(); i++) 
//    {
//        modelSalsa.removeRow(i);
//        i-=1;
//    }
//    while(iterador.getCancion()!=null)
//    {
//        if(iterador.getGenero()==1)
//        {
//            modelSalsa.addRow(new Object[]{iterador.getCancion()});
//        }
//        iterador = iterador.siguiente;
//    }
//}
//public void Imprimir_TableRock(){
//    Nodo iterador = playlist.primero;
//    DefaultTableModel modelRock = (DefaultTableModel) jTrock.getModel();
//    modelRock.addRow(new Object[]{" "});
//    for (int i = 0; i < jTrock.getRowCount(); i++) 
//    {
//        modelRock.removeRow(i);
//        i-=1;
//    }
//    while(iterador.getCancion()!=null)
//    {
//        if(iterador.getGenero()==2)
//        {
//            modelRock.addRow(new Object[]{iterador.getCancion()});
//        }
//        iterador = iterador.siguiente;
//    }
//}

    private void BtmAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtmAgregarActionPerformed
      //Programar función de las listas
      if(jRsalsa.isSelected()==true)
      {
          playlist.insertar(TxtCancion.getText(), 1);
          Imprimir_TableGeneral();
          
      }else{
          playlist.insertar(TxtCancion.getText(), 2);
          Imprimir_TableGeneral();
      }
      
      /*
      DefaultTableModel model = (DefaultTableModel) jTsalsa.getModel();
      DefaultTableModel modelGeneral = (DefaultTableModel) jtGeneral.getModel();
      modelGeneral.addRow(new Object[]{playlist.primero.getCancion()});
      model.addRow(new Object[]{playlist.primero.getCancion()});*/
      
      
    }//GEN-LAST:event_BtmAgregarActionPerformed
DefaultTableModel modelo = new DefaultTableModel();
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /*DefaultTableModel model = (DefaultTableModel) jTsalsa.getModel();
        model.addRow(new Object[]{"Salsa1"});*/
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(spotify1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(spotify1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(spotify1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(spotify1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new spotify1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtmAgregar;
    private javax.swing.JTextField TxtCancion;
    public static javax.swing.ButtonGroup genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRrock;
    private javax.swing.JRadioButton jRsalsa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTrock;
    private javax.swing.JTable jTsalsa;
    private javax.swing.JTable jtGeneral;
    // End of variables declaration//GEN-END:variables
}
